# Generated by Django 5.2.4 on 2025-08-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_firs_name_user_last_name_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firs_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_verifired',
            new_name='is_verified',
        ),
    ]
