# Generated by Django 5.2.4 on 2025-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_image_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
